### ISSUE TITLE
The equality constraints defined in reference splince smoothing

### ISSUE THREAD

**Issue by GPrathap** [LiJiangnanBit/path_optimizer_2#7]
I'm not sure if the equality constraints defined in line 126 and 127 are correct. Can you please take a look and let me know?

https://github.com/LiJiangnanBit/path_optimizer_2/blob/39948acf52c37c00cc9fae1a27b9988eaf8c0cbc/src/reference_path_smoother/tension_smoother_2.cpp#L126

I guess, those should be 

       cons(cons_x_update_start_index + i, theta_start_index + i) = - ds * cos(angle_list[i]);
        cons(cons_y_update_start_index + i, theta_start_index + i) = -ds * sin(angle_list[i]);

**Comment by BorisVandermeer** [comment]
The original is right. Because the theta here is an "update theata",which is a small number,  x - x_ref = ds * cos(originalangle+theta) = ds * sin(originalangle)*theta;

**Comment by GPrathap** [comment]
Yeap, makes sense now , thank youu
